DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `Id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `CreateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE TIME',
  `UserName` varchar(30) CHARACTER SET utf8 NOT NULL COMMENT 'UserName',
  `Password` varchar(45) CHARACTER SET utf8 NOT NULL COMMENT 'password',
  `RealName` varchar(45) CHARACTER SET utf8 NOT NULL COMMENT 'RealName',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;